version: '3'
services:
  chatbot_be:
    build:
      dockerfile: ./Dockerfile
      context: ApiGateway
    container_name: chatbot_be
    ports:
      - "8081:80"
  chatbot_ui:
    build:
      dockerfile: ./Dockerfile
      context: nx
    container_name: chatbot_ui
    environment:
      - REACT_APP_API_URL=chatbot_be:80
    depends_on:
      - chatbot_be
    ports:
      - "3000:3000"
  discord_chatbot:
    build:
      dockerfile: ./Dockerfile
      context: ChatbotDiscord
    environment:
      - TOKEN=MTE4ODUxODU4ODgxMDgwMTE5NA.GEAqD4.vx0iQ9lz5JNfhvx1oQCLO3hhs3hGCTuBscLkKM
    container_name: discord_chatbot
  